import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "./components/Button/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button
          className={styles.homeBtn}
          onClick={() => alert("Hello")}
          disabled={true}
        >
          Hello Rami
        </Button>

        <Button
          className={styles.btnFullWidth}
          onClick={() => alert("Hello")}
          variant="secondary"
        >
          Hello Rami
        </Button>
      </main>
    </>
  );
}
